### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by francicco** [UTbioinf/SMSC#1]
Hi,

while compailing I go this error:

```
Scanning dependencies of target base
[  2%] Building C object mummer-lib/libbasedir/CMakeFiles/base.dir/cleanMUMcand.c.o
[  4%] Building C object mummer-lib/libbasedir/CMakeFiles/base.dir/multiseq.c.o
[  6%] Building C object mummer-lib/libbasedir/CMakeFiles/base.dir/safescpy.c.o
[  8%] Building C object mummer-lib/libbasedir/CMakeFiles/base.dir/space.c.o
[ 10%] Building C object mummer-lib/libbasedir/CMakeFiles/base.dir/clock.c.o
[ 12%] Building C object mummer-lib/libbasedir/CMakeFiles/base.dir/mapfile.c.o
[ 14%] Building C object mummer-lib/libbasedir/CMakeFiles/base.dir/procopt.c.o
[ 16%] Building C object mummer-lib/libbasedir/CMakeFiles/base.dir/seterror.c.o
[ 18%] Linking C static library libbase.a
[ 18%] Built target base
Scanning dependencies of target stree
[ 20%] Building C object mummer-lib/streesrc/CMakeFiles/stree.dir/access.c.o
In file included from /home/fc464/software/SMSC/mummer-lib/streesrc/access.c:12:0:
/home/fc464/software/SMSC/mummer-lib/streesrc/streedef.h:11:19: fatal error: types.h: No such file or directory
 #include "types.h"
                   ^
compilation terminated.
make[2]: *** [mummer-lib/streesrc/CMakeFiles/stree.dir/access.c.o] Error 1
make[1]: *** [mummer-lib/streesrc/CMakeFiles/stree.dir/all] Error 2
make: *** [all] Error 2
```

How do I fix it?
Thanks a lot
F

**Comment by zijuexiansheng** [comment]
Hi @francicco, I just made a fix to this issue. Hopefully it works

**Comment by francicco** [comment]
Hi @zijuexiansheng,

Thanks a lot, it goes everything fine till...

```
[ 18%] Built target base
[ 46%] Built target stree
[ 67%] Built target mummer
[ 83%] Built target common-bio
[ 87%] Built target blasrm5_filter
[ 89%] Building CXX object src.2.2.1/CMakeFiles/smsc.dir/smsc.cpp.o
[ 91%] Building CXX object src.2.2.1/CMakeFiles/smsc.dir/mummer_api.cpp.o
[ 93%] Building C object src.2.2.1/CMakeFiles/smsc.dir/threadpool.c.o
[ 95%] Building CXX object src.2.2.1/CMakeFiles/smsc.dir/path_cover.cpp.o
[ 97%] Building CXX object src.2.2.1/CMakeFiles/smsc.dir/msa_consensus.cpp.o
[100%] Linking CXX executable smsc
/usr/bin/ld: cannot find -lemon
collect2: error: ld returned 1 exit status
make[2]: *** [src.2.2.1/smsc] Error 1
make[1]: *** [src.2.2.1/CMakeFiles/smsc.dir/all] Error 2
make: *** [all] Error 2
```

How do I fix this? Some settings for lemon to fix?

Thanks
F

**Comment by francicco** [comment]
In the attempt to fix this what I did was change the `src.2.2.1/CMakeFiles/smsc.dir/link.txt` from

`/usr/bin/c++  -O3 -DNDEBUG   CMakeFiles/smsc.dir/smsc.cpp.o CMakeFiles/smsc.dir/mummer_api.cpp.o CMakeFiles/smsc.dir/threadpool.c.o CMakeFiles/smsc.dir/path_cover.cpp.o CMakeFiles/smsc.dir/msa_consensus.cpp.o  -o smsc ../common-bio/libcommon-bio.a ../mummer-lib/libmummer.a ../mummer-lib/libbasedir/libbase.a ../mummer-lib/streesrc/libstree.a -lpthread ../mummer-lib/libbasedir/libbase.a`

to

`/usr/bin/c++  -O3 -DNDEBUG   CMakeFiles/smsc.dir/smsc.cpp.o CMakeFiles/smsc.dir/mummer_api.cpp.o CMakeFiles/smsc.dir/threadpool.c.o CMakeFiles/smsc.dir/path_cover.cpp.o CMakeFiles/smsc.dir/msa_consensus.cpp.o  -o smsc ../common-bio/libcommon-bio.a ../mummer-lib/libmummer.a ../mummer-lib/libbasedir/libbase.a ../mummer-lib/streesrc/libstree.a -lpthread ../mummer-lib/libbasedir/libbase.a /home/fc464/software/lemon-1.3.1/build/lemon/libemon.a`

is that alright?
Best,
F

**Comment by francicco** [comment]
A side question? Can I use high-coverage (70-fold) non-corrected PacBio data instead of corrected reads, if not what tools can I use to correct the reads? Unfortunately I have low-coverage (10-fold) illumina reads only.

Best
F

**Comment by zijuexiansheng** [comment]
> In the attempt to fix this what I did was change the `src.2.2.1/CMakeFiles/smsc.dir/link.txt` from
> 
> `/usr/bin/c++ -O3 -DNDEBUG CMakeFiles/smsc.dir/smsc.cpp.o CMakeFiles/smsc.dir/mummer_api.cpp.o CMakeFiles/smsc.dir/threadpool.c.o CMakeFiles/smsc.dir/path_cover.cpp.o CMakeFiles/smsc.dir/msa_consensus.cpp.o -o smsc ../common-bio/libcommon-bio.a ../mummer-lib/libmummer.a ../mummer-lib/libbasedir/libbase.a ../mummer-lib/streesrc/libstree.a -lpthread ../mummer-lib/libbasedir/libbase.a`
> 
> to
> 
> `/usr/bin/c++ -O3 -DNDEBUG CMakeFiles/smsc.dir/smsc.cpp.o CMakeFiles/smsc.dir/mummer_api.cpp.o CMakeFiles/smsc.dir/threadpool.c.o CMakeFiles/smsc.dir/path_cover.cpp.o CMakeFiles/smsc.dir/msa_consensus.cpp.o -o smsc ../common-bio/libcommon-bio.a ../mummer-lib/libmummer.a ../mummer-lib/libbasedir/libbase.a ../mummer-lib/streesrc/libstree.a -lpthread ../mummer-lib/libbasedir/libbase.a /home/fc464/software/lemon-1.3.1/build/lemon/libemon.a`
> 
> is that alright?
> Best,
> F

Hmmmm, I doubt that would work since the header files of lemon would be missing. If that works, it should be fine.

When I made the code public, I assumed that the Lemon library is installed in a way such that the headers and static/dynamic libraries are accessible by the compiler. I have better ways to fix this and I will completely fix this issue later when I have time, so please **do not** close this issue.

Right now, I guess the following is probably an easier way.

It seems that you only built lemon but did not install it. Could you also install it in your `lemon-1.3.1/build/local` directory? I used to do the following

```
tar xf lemon-1.3.1.tar.gz
cd lemon-1.3.1
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/local -DCMAKE_BUILD_TYPE=Release -DLEMON_ENABLE_COIN=NO -DLEMON_ENABLE_ILOG=NO
make -j 8
make check
make install
```
And then, add the paths to the headers and the static libraries to the environment variables:

```
export C_INCLUDE_PATH=${C_INCLUDE_PATH}:/home/fc464/software/lemon-1.3.1/build/local/include
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:/home/fc464/software/lemon-1.3.1/build/local/include
export LIBRARY_PATH=${LIBRARY_PATH}:/home/fc464/software/lemon-1.3.1/build/local/lib
```

After these steps, go to the SMSC directory and run `make` again.

**Comment by zijuexiansheng** [comment]
> A side question? Can I use high-coverage (70-fold) non-corrected PacBio data instead of corrected reads, if not what tools can I use to correct the reads? Unfortunately I have low-coverage (10-fold) illumina reads only.
> 
> Best
> F

I am not sure if non-corrected reads work well. Since this is my first project (code is nasty as you can see) and I wanted to make the project easier, I assumed that the long reads are error corrected. I also tried to close some alignment gaps. If the error rate is high, then closing alignment gaps will lead to dramatic mistake.

I would recommend to use Canu to error correct your PacBio long reads, which is also a good genome assembly tool.

**Comment by francicco** [comment]
I actually used CANU to assemble these genomes. Where the error corrected reads are?

I'll try you're way to compile it
Thanks
F

**Comment by zijuexiansheng** [comment]
> I actually used CANU to assemble these genomes. Where the error corrected reads are?
> 
> I'll try you're way to compile it
> Thanks
> F

The `<prefix>.correctedReads.fasta.gz` file generated by Canu has the corrected reads

**Comment by francicco** [comment]
Thank you!
F

**Comment by francicco** [comment]
Nothing...

```
[fc464@login-e-13 build]$ echo $CPLUS_INCLUDE_PATH
/home/fc464/software//lemon-1.3.1/build/local/include
[fc464@login-e-13 build]$ echo $LD_LIBRARY_PATH
/usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-5.4.0/ncurses-6.0-qe3zsbdgaja5toda6pdkjkgxhke4dgnl/lib:/usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-5.4.0/htslib-1.9-p2taavlu3ieppo25otjfgvfu5tysbgho/lib:/usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-5.4.0/sqlite-3.20.0-gxy4jnkgk5uqfwiigo3n6ti4wpk7oflg/lib:/usr/local/Cluster-Apps/gcc/5.2.0/lib64:/usr/local/Cluster-Apps/gcc/5.2.0/lib:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/daal/lib/intel64_lin:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/ipp/lib/intel64:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/tbb/lib/intel64/gcc4.7:/usr/local/Cluster-Apps/intel/2017.4/debugger_2017/iga/lib:/usr/local/Cluster-Apps/intel/2017.4/debugger_2017/libipt/intel64/lib:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/mpi/intel64/lib:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/tbb/lib/intel64_lin/gcc4.7:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64_lin:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/compiler/lib/intel64:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/compiler/lib/intel64_lin:/usr/local/software/global/lib:/usr/local/Cluster-Apps/vgl/2.5.1/64/lib:/usr/local/software/slurm/current/lib:/home/fc464/software//bamtools-2.5.1/lib64:/home/fc464/software//SuiteSparse/COLAMD:/rds/user/fc464/hpc-work/SoftwareTwo/KAT/lib:/home/fc464/software//bamtools-2.5.1/lib64:/home/fc464/software//SuiteSparse/COLAMD:/rds/user/fc464/hpc-work/SoftwareTwo/KAT/lib:/home/fc464/software//lemon-1.3.1/build/local/lib:/home/fc464/software//bamtools-2.5.1/lib64:/home/fc464/software//SuiteSparse/COLAMD:/rds/user/fc464/hpc-work/SoftwareTwo/KAT/lib:/home/fc464/software//lemon-1.3.1/build/local/lib
[fc464@login-e-13 build]$ echo $C_INCLUDE_PATH
/home/fc464/software//lemon-1.3.1/build/local/include

[fc464@login-e-13 build]$ make
[  6%] Built target blasrm5_filter
[ 22%] Built target base
[ 51%] Built target stree
[ 71%] Built target mummer
[ 87%] Built target common-bio
[ 89%] Linking CXX executable smsc
/usr/bin/ld: cannot find -lemon
collect2: error: ld returned 1 exit status
make[2]: *** [src.2.2.1/smsc] Error 1
make[1]: *** [src.2.2.1/CMakeFiles/smsc.dir/all] Error 2
make: *** [all] Error 2
```
:(

**Comment by zijuexiansheng** [comment]
> Nothing...
> 
> ```
> [fc464@login-e-13 build]$ echo $CPLUS_INCLUDE_PATH
> /home/fc464/software//lemon-1.3.1/build/local/include
> [fc464@login-e-13 build]$ echo $LD_LIBRARY_PATH
> /usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-5.4.0/ncurses-6.0-qe3zsbdgaja5toda6pdkjkgxhke4dgnl/lib:/usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-5.4.0/htslib-1.9-p2taavlu3ieppo25otjfgvfu5tysbgho/lib:/usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-5.4.0/sqlite-3.20.0-gxy4jnkgk5uqfwiigo3n6ti4wpk7oflg/lib:/usr/local/Cluster-Apps/gcc/5.2.0/lib64:/usr/local/Cluster-Apps/gcc/5.2.0/lib:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/daal/lib/intel64_lin:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/ipp/lib/intel64:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/tbb/lib/intel64/gcc4.7:/usr/local/Cluster-Apps/intel/2017.4/debugger_2017/iga/lib:/usr/local/Cluster-Apps/intel/2017.4/debugger_2017/libipt/intel64/lib:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/mpi/intel64/lib:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/tbb/lib/intel64_lin/gcc4.7:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64_lin:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/compiler/lib/intel64:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/compiler/lib/intel64_lin:/usr/local/software/global/lib:/usr/local/Cluster-Apps/vgl/2.5.1/64/lib:/usr/local/software/slurm/current/lib:/home/fc464/software//bamtools-2.5.1/lib64:/home/fc464/software//SuiteSparse/COLAMD:/rds/user/fc464/hpc-work/SoftwareTwo/KAT/lib:/home/fc464/software//bamtools-2.5.1/lib64:/home/fc464/software//SuiteSparse/COLAMD:/rds/user/fc464/hpc-work/SoftwareTwo/KAT/lib:/home/fc464/software//lemon-1.3.1/build/local/lib:/home/fc464/software//bamtools-2.5.1/lib64:/home/fc464/software//SuiteSparse/COLAMD:/rds/user/fc464/hpc-work/SoftwareTwo/KAT/lib:/home/fc464/software//lemon-1.3.1/build/local/lib
> [fc464@login-e-13 build]$ echo $C_INCLUDE_PATH
> /home/fc464/software//lemon-1.3.1/build/local/include
> 
> [fc464@login-e-13 build]$ make
> [  6%] Built target blasrm5_filter
> [ 22%] Built target base
> [ 51%] Built target stree
> [ 71%] Built target mummer
> [ 87%] Built target common-bio
> [ 89%] Linking CXX executable smsc
> /usr/bin/ld: cannot find -lemon
> collect2: error: ld returned 1 exit status
> make[2]: *** [src.2.2.1/smsc] Error 1
> make[1]: *** [src.2.2.1/CMakeFiles/smsc.dir/all] Error 2
> make: *** [all] Error 2
> ```
> 
> :(

Can you show me the `LIBRARY_PATH` rather than `LD_LIBRARY_PATH`? `LD_LIBRARY_PATH` is for shared library. But I think you probably only have a static library for lemon.

**Comment by francicco** [comment]
```
[fc464@login-e-12 ~]$ echo $LIBRARY_PATH
/usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-5.4.0/ncurses-6.0-qe3zsbdgaja5toda6pdkjkgxhke4dgnl/lib:/usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-5.4.0/htslib-1.9-p2taavlu3ieppo25otjfgvfu5tysbgho/lib:/usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-5.4.0/sqlite-3.20.0-gxy4jnkgk5uqfwiigo3n6ti4wpk7oflg/lib:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/daal/lib/intel64_lin:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/ipp/lib/intel64:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/tbb/lib/intel64/gcc4.7:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/tbb/lib/intel64_lin/gcc4.7:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/compiler/lib/intel64_lin:/usr/local/Cluster-Apps/intel/2017.4/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64_lin
```

**Comment by zijuexiansheng** [comment]
Hi @francicco, can you try the new installing method? I put all the dependencies together except for BLASR. This one should be easier to install.

**Comment by francicco** [comment]
I added the lemon path to the `$LIBRARY_PATH`, the installation is now complete.

I'd like to ask you a couple of thinks

- I would like you to ask if would be possible to implement minimap2 to do the alignment, it is pretty efficinet. I have a coverage of 80-fold, it not really feasible to map them using nucmer.
- I don't understand the best way to use the program, what about the `-m -b` flags, how to use them.

Thanks a lot
F

**Comment by zijuexiansheng** [comment]
> I added the lemon path to the `$LIBRARY_PATH`, the installation is now complete.
> 
> I'd like to ask you a couple of thinks
> 
> * I would like you to ask if would be possible to implement minimap2 to do the alignment, it is pretty efficinet. I have a coverage of 80-fold, it not really feasible to map them using nucmer.
> * I don't understand the best way to use the program, what about the `-m -b` flags, how to use them.
> 
> Thanks a lot
> F

* I don't think I would add minimap2 within the next 2~3 months. Can you open a new issue and request for this feature? I can't promise you I will add it soon. But just in case I add it some day, you will be notified.
* The `-m -b` flags are probably mostly useful for myself to debug the code. You probably can ignore these two parameters completely. The program has been partitioned into four segments in general, `preprocessing`, `alignment and consensus` (`-m` flag), `bridging` (`-b`), and `remaining steps`. The two steps in the middle are time consuming so I can set those flags to start running the program in the middle.

**Comment by zijuexiansheng** [comment]
@francicco I am closing this issue since I have tried to compile the latest updated version on two machines with no errors. If you have any more questions, please open a new issue. Thank you very much!
