### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by pdimens** [UTbioinf/SMSC#2]
Hello, I read through the previously closed issue #1 , but I'm unclear if my error is different. The issue again appears to be with `lemon` and takes the form of:
```
[ 95%] Built target adaptors_test
[ 96%] Linking CXX executable graph_copy_test
[ 96%] Built target graph_copy_test
[ 97%] Linking CXX executable tsp_test
[ 97%] Built target tsp_test
[ 98%] Linking CXX executable lgf_reader_writer_test
[ 98%] Built target lgf_reader_writer_test
make[1]: *** [CMakeFiles/Makefile2:168: CMakeFiles/check.dir/rule] Error 2
make: *** [Makefile:210: check] Error 2
Traceback (most recent call last):
  File "./install.py", line 173, in <module>
    main()
  File "./install.py", line 166, in main
    (add_config, mummer_dirname, mhap_jar, muscle_exe)
  File "/mnt/secondary/pdimens/yft_genome/scaffolding/src/SMSC/loon_install/multitool_install.py", line 266, in run
    self.install_cpp()
  File "/mnt/secondary/pdimens/yft_genome/scaffolding/src/SMSC/loon_install/multitool_install.py", line 221, in install_cpp
    each[0](self, cmd_args, *each[1:])
  File "./install.py", line 33, in add_lemon_parameters
    lemon_path = install_lemon.install_lemon( os.path.join(obj.source_dir, "depends"), obj.install["libexec"] )
  File "/mnt/secondary/pdimens/yft_genome/scaffolding/src/SMSC/loon_install/install_lemon.py", line 41, in install_lemon
    subprocess.check_call( ["make", "-j", n_cpu, "check"] )
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '40', 'check']' returned non-zero exit status 2
```

**Comment by pdimens** [comment]
further diagnosis reveals that `make check` on manually building `lemon` as you suggested in the other issue discussion fails. 

```
[ 71%] Building CXX object test/CMakeFiles/maps_test.dir/maps_test.cc.o
In file included from /home/pdimens/secondary/pdimens/yft_genome/scaffolding/SMSC/depends/lemon-1.3.1/test/maps_test.cc:24:
/home/pdimens/secondary/pdimens/yft_genome/scaffolding/SMSC/depends/lemon-1.3.1/lemon/maps.h: In substitution of ‘template<class K, class V, V v> lemon::ConstMap<K, lemon::Const<V, v> > lemon::constMap() [with K = A; V = B; V v = <missing>]’:
/home/pdimens/secondary/pdimens/yft_genome/scaffolding/SMSC/depends/lemon-1.3.1/test/maps_test.cc:120:26:   required from here
/home/pdimens/secondary/pdimens/yft_genome/scaffolding/SMSC/depends/lemon-1.3.1/lemon/maps.h:193:36: error: non-type template parameters of class type only available with ‘-std=c++2a’ or ‘-std=gnu++2a’
  193 |   inline ConstMap<K, Const<V, v> > constMap() {
      |                                    ^~~~~~~~
/home/pdimens/secondary/pdimens/yft_genome/scaffolding/SMSC/depends/lemon-1.3.1/lemon/maps.h: In substitution of ‘template<class K, class V, V v> lemon::ConstMap<K, lemon::Const<V, v> > lemon::constMap() [with K = A; V = lemon::Const<int, 10>; V v = <missing>]’:
/home/pdimens/secondary/pdimens/yft_genome/scaffolding/SMSC/depends/lemon-1.3.1/test/maps_test.cc:136:39:   required from here
/home/pdimens/secondary/pdimens/yft_genome/scaffolding/SMSC/depends/lemon-1.3.1/lemon/maps.h:193:36: error: non-type template parameters of class type only available with ‘-std=c++2a’ or ‘-std=gnu++2a’
... (there's more, but this is the part with the error)
```

**Comment by zijuexiansheng** [comment]
Hi @pdimens , can you show me your compiler version? GCC or Clang, etc? I've never really seen a compiling issue with Lemon before. So I am not quite sure about what is really happening. But it looks more like an issue of compiler version to me.

**Comment by pdimens** [comment]
Absolutely.

gcc: 9.1.0-2
clang: 8.0.1-1

**Comment by zijuexiansheng** [comment]
It's the problem with gcc-9.1.0. I guess cmake choose your gcc as the default compiler. I don't have clang of version 8.0.1 so I didn't try it. But I guess it will work.

You can do the following (assuming you are in the directory of the SMSC repo): 

```
rm -rf depends/lemon-1.3.1 depends/build_lemon
rm -rf build/
export CC=`which clang`
export CXX=`which clang++`
```
and then run the `install.py` to reinstall it.

My `install.py` doesn't do cleaning so you probably need the two `rm` commands above to manually remove the intermediate files. The two `export` commands will force cmake to choose clang as the compiler.

**Comment by pdimens** [comment]
Thank you for looking into it. I have done as you said and here is the outcome:

```
[ 83%] Built target heap_test
8 warnings generated.
[ 84%] Linking CXX executable min_cost_arborescence_test
[ 84%] Built target min_cost_arborescence_test
146 warnings generated.
[ 85%] Linking CXX executable graph_test
[ 85%] Built target graph_test
50 warnings generated.
[ 86%] Linking CXX executable graph_utils_test
[ 86%] Built target graph_utils_test
21 warnings generated.
[ 87%] Linking CXX executable planarity_test
[ 87%] Built target planarity_test
66 warnings generated.
[ 88%] Linking CXX executable maps_test
[ 88%] Built target maps_test
[ 89%] Linking CXX executable matching_test
[ 89%] Built target matching_test
35 warnings generated.
[ 91%] Linking CXX executable min_cost_flow_test
[ 91%] Built target min_cost_flow_test
1 warning generated.
[ 92%] Linking CXX executable graph_copy_test
[ 92%] Built target graph_copy_test
59 warnings generated.
[ 93%] Linking CXX executable tsp_test
[ 93%] Built target tsp_test
[ 94%] Linking CXX executable lgf_reader_writer_test
[ 94%] Built target lgf_reader_writer_test
make[1]: *** [CMakeFiles/Makefile2:168: CMakeFiles/check.dir/rule] Error 2
make: *** [Makefile:210: check] Error 2
Traceback (most recent call last):
  File "./install.py", line 173, in <module>
    main()
  File "./install.py", line 166, in main
    (add_config, mummer_dirname, mhap_jar, muscle_exe)
  File "/mnt/secondary/pdimens/yft_genome/scaffolding/SMSC/loon_install/multitool_install.py", line 266, in run
    self.install_cpp()
  File "/mnt/secondary/pdimens/yft_genome/scaffolding/SMSC/loon_install/multitool_install.py", line 221, in install_cpp
    each[0](self, cmd_args, *each[1:])
  File "./install.py", line 33, in add_lemon_parameters
    lemon_path = install_lemon.install_lemon( os.path.join(obj.source_dir, "depends"), obj.install["libexec"] )
  File "/mnt/secondary/pdimens/yft_genome/scaffolding/SMSC/loon_install/install_lemon.py", line 41, in install_lemon
    subprocess.check_call( ["make", "-j", n_cpu, "check"] )
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '40', 'check']' returned non-zero exit status 2
```

**Comment by pdimens** [comment]
lemon installs without issue on archlinux via the `AUR`. Is there a way to point install.py to use the system installation?

**Comment by zijuexiansheng** [comment]
Is your clang linked to your gcc-9.1.0? If that is the case, you probably need to use an older compiler. I am not sure what happens to gcc-9, but older compilers should work. I just tried gcc-8.3, and previously I tried gcc-4.8, gcc-6 and gcc-7.

**Comment by zijuexiansheng** [comment]
> lemon installs without issue on archlinux via the `AUR`. Is there a way to point install.py to use the system installation?

I think it should be able to use the system installation directly. But let me double check

**Comment by zijuexiansheng** [comment]
> lemon installs without issue on archlinux via the `AUR`. Is there a way to point install.py to use the system installation?

The current code does not. But yes, you can do that by changing the `add_lemon_parameters(obj, cmd_args)` in `install.py`.

* First locate your lemon installation directory by the command `which dimacs-solver`.
* Let's say the output is `/usr/local/bin/dimacs-solver`. Then you'll need check if the file the directory `/usr/local/share/lemon/cmake` has the file `LEMONConfig.cmake`
* If it does, then change the `add_lemon_parameters(obj, cmd_args)` in `install.py` to

```
def add_lemon_parameters(obj, cmd_args):
    cmd_args.append("-DLEMON_DIR={}".format("/usr/local/local/share/lemon/cmake"))
```

There should be another way around if you can't find the `LEMONConfig.cmake`. But let's see if this one works

**Comment by pdimens** [comment]
It goes on for a while after this error message, with other subsequent errors (below). I'm no expert in C or CPP, but it looks like it's still trying to use the `lemon` that's provided by SMSC

```
[ 82%] Built target circulation_test
[ 84%] Built target nagamochi_ibaraki_test
[ 85%] Building CXX object test/CMakeFiles/dfs_test.dir/dfs_test.cc.o
[ 87%] Built target random_test
[ 89%] Built target path_test
[ 92%] Built target tsp_test
[ 94%] Built target gomory_hu_test
In file included from /mnt/secondary/pdimens/yft_genome/scaffolding/SMSC/depends/lemon-1.3.1/test/adaptors_test.cc:24:
In file included from /mnt/secondary/pdimens/yft_genome/scaffolding/SMSC/depends/lemon-1.3.1/lemon/bfs.h:31:
/mnt/secondary/pdimens/yft_genome/scaffolding/SMSC/depends/lemon-1.3.1/lemon/path.h:231:24: error: 
      no viable conversion from 'typename PredMapPath<ResidualDigraph<ListDigraph, ArcMap<int>,
      ArcMap<int>, Tolerance<int> >, NodeMap<Arc> >::RevArcIt' to
      'std::vector<lemon::UndirectorBase<const lemon::ListDigraph>::Arc,
      std::allocator<lemon::UndirectorBase<const lemon::ListDigraph>::Arc> >::value_type' (aka
      'lemon::UndirectorBase<const lemon::ListDigraph>::Arc')
        head.push_back(it);
                       ^~
```

does this line matter for that?
```
lemon_path = install_lemon.install_lemon( os.path.join(obj.source_dir, "depends"), oobj.install["libexec"] )
```

**Comment by zijuexiansheng** [comment]
did you do `rm -rf build/` before running `install.py`? I probably should've added a `--clean` option to it. 

The function `add_lemon_parameters` checks if the lemon in `depends/` directory is installed. If not, it will compile it. The line you are asking is to check if this version of lemon is installed.  You should replace the **whole** function `add_lemon_parameters` with the one I provided above.

**Comment by zijuexiansheng** [comment]
@pdimens I just added some lines of code to first check if there is a system installation of Lemon available. Can you see if that works?

**Comment by pdimens** [comment]
Ah, that did it! replacing the whole function worked.

**Comment by pdimens** [comment]
Clone the updated repo into a fresh folder and ran `install.py`, and everything compiled successfully :smile: 

Thank you so much for your assistance with this!

**Comment by zijuexiansheng** [comment]
> Clone the updated repo into a fresh folder and ran `install.py`, and everything compiled successfully 😄
> 
> Thank you so much for your assistance with this!

Sure

**Comment by zijuexiansheng** [comment]
`gcc-9.1` or the clang linked to this version of gcc has a problem compiling `Lemon`. There are two solutions to this issue: 

1. Use a lower version gcc (gcc-4.8, gcc-6, gcc-7, gcc-8.3 have been tested). Make sure to use `export CC=<gcc path>` and `export CXX=<g++ path>` so that cmake will be able to detect and use it.
2.  Or, you can install Lemon by yourself. If you choose to install Lemon by yourself, please use the command `ls $(dirname $(which dimacs-solver))/../share/lemon/cmake/LEMONConfig.cmake` to make sure the `LEMONConfig.cmake` file exists.
